# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Siddharth Karamcheti
email: skaramcheti@cs.stanford.edu
description: >- # this means to ignore newlines until "baseurl:"
  First-year PhD Student in Computer Science at Stanford. Interested in grounded language
  understanding and interaction, building agents that can collaborate with humans and grow more capable over time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://siddkaramcheti.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: siddkaramcheti
github_username:  siddk
author: Siddharth Karamcheti
facebook_image: "/assets/img/sidd.jpg"
twitter_image: "/assets/img/sidd.jpg"

# Google Analytics
google_analytics: UA-65310310-1

# Build settings
markdown: kramdown
theme: jekyll-whiteglass
plugins:
  - jekyll-sitemap

## Travis CI
plugins_dir: ./_plugins
jekyll_get:
  - data: github
    json: 'https://api.github.com/users/siddk/repos'
    cache: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
